### ISSUE TITLE
callback function

### ISSUE THREAD

**Issue by ersenturgut** [michaelrafailyk/stickymate#11]
Hi

Is it possible to add callback function while steps of animation? This would be nice. We can make ajax call for example...is there any way to add this option quickly?

thanks...

**Comment by rafailyk** [comment]
> Hi
> 
> Is it possible to add callback function while steps of animation? This would be nice. We can make ajax call for example...is there any way to add this option quickly?
> 
> thanks...

Hello! Unfortunately right now i’m super busy and not to possible include this feature right now. Thank you for your interest and sorry that can’t help you right now.
